# When modifying this file, please validate using
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

component_management:
  individual_components:
    - component_id: app
      name: qpdf
      paths:
        - qpdf/qpdf.cc
        - qpdf/fix-qdf.cc
    - component_id: lib
      name: libqpdf
      paths:
        - qpdflib/*
        - qpdflib/qpdf/*
    - component_id: examples
      name: examples
      paths:
        - examples/*

ignore:
  - fuzz/**/*
  - compare-for-test/**/*
  - libtests/**/*
  - qpdf/test*
